---
language: node_js
node_js:
  - "6"

dist: trusty

addons:
  chrome: stable

cache:
  yarn: true

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn global add greenkeeper-lockfile@1

install:
  - yarn install --no-lockfile --non-interactive

before_script:
  - greenkeeper-lockfile-update

script:
  - yarn test

after_script:
  - yarn run test:coverage
  - greenkeeper-lockfile-upload
